name: Zip shell script files

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: zip files
        run: |
          zip -r src/ .
      - uses: actions/upload-artifact@main
        with:
          name: my-artifact
          path: public/
